export default {
  tabSelection: '采购入库',
  activeIndex: '1',
  IASelection: '转库申请单',
  userInfo: {},
  // 0表示新建订单，1表示编辑订单
  // 销售订单部分
  saleOrderData: {},
  saleOrderState: 0,
  currentSaleOrder: {},
  currentSaleOrderDetail: {},
  newSaleOrder: {},
  // 登录时存储的公共部分
  allInventoryOrganizations: [],
  // 中心库存部分
  inventoryTransferState: 0,
  newTransferReq: {},
  // 库存盘点表头
  currentInventoryCheck: {},
  // 库存盘点状态
  inventoryCheckState: 1,
  // 中心其他入库状态
  centerOtherInState: 0,
  // 中心其他入库表头
  centerOtherInHead: {},
  // 请购状态
  purchaseState: 0,
  purchaseReq: {},
  purchaseGoods: [],
  // 采购合同状态
  contractState: 0,
  contractMain: {},
  contractGoods: [],
  // 采购入库状态
  purchaseIntoState: 0,
  purchaseIntoMain: {},
  purchaseIntoDetail: [],
  // 期初库存状态
  initState: 0,
  initMain: {},
  initDetail: []

}
